# Generated by Django 4.2.30 on 2026-04-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('debtor_name', models.CharField(max_length=200)),
                ('debtor_location', models.CharField(max_length=200)),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('debt_type', models.CharField(choices=[('commercial', 'Commercial Debt'), ('invoice', 'Invoice Unpaid'), ('loan', 'Loan Default'), ('lease', 'Lease / Rent'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=2)),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('in_progress', 'In Progress'), ('negotiation', 'Negotiation'), ('legal', 'Legal Proceedings'), ('settled', 'Settled'), ('closed', 'Closed')], default='new', max_length=20)),
                ('assigned_agent', models.CharField(blank=True, max_length=200)),
                ('internal_notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
